apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "foam-outbox.fullname" . }}
  labels:
    {{- include "foam-outbox.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "foam-outbox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "foam-outbox.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "foam-outbox.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: outbox
              containerPort: 4444
              protocol: TCP
{{/*          livenessProbe:*/}}
{{/*            exec:*/}}
{{/*              command:*/}}
{{/*                - /bin/sh*/}}
{{/*                - -c*/}}
{{/*                - netstat -an | grep -q ':4444 '*/}}
{{/*            initialDelaySeconds: 120*/}}
{{/*            periodSeconds: 5*/}}
{{/*          readinessProbe:*/}}
{{/*            exec:*/}}
{{/*              command:*/}}
{{/*                - /bin/sh*/}}
{{/*                - -c*/}}
{{/*                - netstat -an | grep -q ':4444 '*/}}
{{/*            initialDelaySeconds: 30*/}}
{{/*            periodSeconds: 5*/}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: BROKER_HOST
              value: {{ required "A valid MQ host is required" .Values.broker.host | quote }}
            - name: BROKER_PASSWORD
              value: {{ required "A valid MQ host is required" .Values.broker.password | quote }}
            - name: BROKER_PORT
              value: {{ .Values.broker.port | quote }}
            - name: BROKER_USERNAME
              value: {{ .Values.broker.username | quote }}
            - name: BROKER_VHOST
              value: {{ .Values.broker.vhost | quote }}
            - name: BROKER_SSL
              value: {{ .Values.broker.tls.enabled | quote }}
            - name: KEYSTORE_PATH
              value: {{ .Values.broker.tls.keystore.path | quote }}
            - name: KEYSTORE_TYPE
              value: {{ .Values.broker.tls.keystore.type | quote }}
            - name: KEYSTORE_PASSWORD
              value: {{ .Values.broker.tls.keystore.password | quote }}
            - name: OUTBOX_PORT
              value: {{ .Values.service.port | quote }}
            - name: CEGA_ENDPOINT
              value: {{ printf "%s%s" (.Values.cega.host) "/username/%s" | quote }}
            - name: CEGA_ENDPOINT_CREDS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cega.credential_secret }}
                  key: cegaCredentials
          volumeMounts:
            - name: outbox
              mountPath: "/ega/outbox"
            - name: java-certs
              mountPath: "/etc/ssl/certs/java"
            - name: java-keystore
              mountPath: "/keystore"
            - name: certs
              mountPath: "/opt/certs"
      volumes:
        - name: outbox
          persistentVolumeClaim:
            claimName: {{ .Values.outbox.pvClaim }}
        - name: java-certs
          secret:
            secretName: {{ required "Name of secret containg Java cacert" .Values.secrets.java | quote }}
        - name: java-keystore
          secret:
            secretName: {{ required "Name of secret containg Java keystore" .Values.secrets.keystore | quote }}
        - name: certs
          secret:
            secretName: {{ required "Secret with tls certs is missing" .Values.secrets.tls | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
