# Default values for sda-foam-integration.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/kkochel/foam-integration
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.3-int"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "foam-sda-integration"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

broker:
  host: "broker-sda-mq"
  port: "5671"
  username: "admin"
  password: "admin"
  vhost: "sda"
  tls:
    enabled: true
    keystore:
      path: "/keystore/keystore.p12"
      type: "PKCS12"
      password: "changeit"

db:
  url: "jdbc:postgresql://postgres-sda-db:5432/sda?ssl=true&sslmode=require&sslrootcert=/opt/certs/ca.crt&sslcert=/opt/certs/client.crt&sslkey=/opt/certs/client.pk8"
  username: "biobank"
  password: "biobank"

app:
  target_queue_name: "foam_dataset"

secrets:
  java: "biobank-ca-cacert"
  keystore: "foam-keystore"
  tls: "foam-certs"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
