apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "foam-app.fullname" . }}
  labels:
    {{- include "foam-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "foam-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "foam-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "foam-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BROKER_HOST
              value: {{ required "A Rabbit MQ host is required" .Values.broker.host | quote }}
            - name: BROKER_PORT
              value: {{ required "A Rabbit MQ port is required" .Values.broker.port | quote }}
            - name: BROKER_USERNAME
              value: {{ required "A Rabbit MQ username is required" .Values.broker.username | quote }}
            - name: BROKER_PASSWORD
              value: {{ required "A Rabbit MQ password is required" .Values.broker.password | quote }}
            - name: BROKER_VHOST
              value: {{ required "A Rabbit MQ vhost is required" .Values.broker.vhost | quote }}
            - name: BROKER_SSL
              value: {{ required "Is communnication with broker use TLS" .Values.broker.tls.enabled | quote }}
            - name: KEYSTORE_PATH
              value: {{ required "The keystore.p12 path is required" .Values.broker.tls.keystore.path | quote | quote }}
            - name: KEYSTORE_TYPE
              value: {{ required "Type of keystore" .Values.broker.tls.keystore.type | quote }}
            - name: KEYSTORE_PASSWORD
              value: {{ required "Password to keystore" .Values.broker.tls.keystore.password | quote }}
            - name: DB_URL
              value: {{ required "A Postgres url is required" .Values.db.url | quote }}
            - name: DB_USERNAME
              value: {{ required "A Postgres user is required" .Values.db.username | quote }}
            - name: DB_PASSWORD
              value: {{ required "A Postgres password is required" .Values.db.password | quote }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: java-cacert
              mountPath: "/etc/ssl/certs/java"
            - name: java-keystore
              mountPath: "/keystore"
      volumes:
        - name: java-cacert
          secret:
            secretName: {{ required "Name of secret containg Java cacert" .Values.secrets.java.cacert | quote }}
        - name: java-keystore
          secret:
            secretName: {{ required "Name of secret containg Java cacert" .Values.secrets.java.keystore | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

